### ISSUE TITLE
add to k.sfconservancy.org?

### ISSUE THREAD

**Issue by pdurbin** [conservancy/reimbursinator#139]
Hi! I was just listening to http://faif.us/cast/2019/apr/02/0x65/ and learned a few things:

- reimbursinator exists
- Software Freedom Conservancy is on GitHub
- Software Freedom Conservancy hosts code at https://k.sfconservancy.org

Should reimbursinator be added to https://k.sfconservancy.org ? I don't see it:

<img width="1303" alt="Screen Shot 2019-04-03 at 9 15 19 AM" src="https://user-images.githubusercontent.com/21006/55481824-30758c00-55f1-11e9-9de0-f10cc08d8a12.png">

**Comment by bkuhn** [comment]
All resolved.  https://GiveUpGitHub.org
